// Generated by gencpp from file learning_topic/ShowStudentResponse.msg
// DO NOT EDIT!


#ifndef LEARNING_TOPIC_MESSAGE_SHOWSTUDENTRESPONSE_H
#define LEARNING_TOPIC_MESSAGE_SHOWSTUDENTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_topic
{
template <class ContainerAllocator>
struct ShowStudentResponse_
{
  typedef ShowStudentResponse_<ContainerAllocator> Type;

  ShowStudentResponse_()
    : name()  {
    }
  ShowStudentResponse_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::learning_topic::ShowStudentResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_topic::ShowStudentResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ShowStudentResponse_

typedef ::learning_topic::ShowStudentResponse_<std::allocator<void> > ShowStudentResponse;

typedef boost::shared_ptr< ::learning_topic::ShowStudentResponse > ShowStudentResponsePtr;
typedef boost::shared_ptr< ::learning_topic::ShowStudentResponse const> ShowStudentResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_topic::ShowStudentResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_topic::ShowStudentResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::learning_topic::ShowStudentResponse_<ContainerAllocator1> & lhs, const ::learning_topic::ShowStudentResponse_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::learning_topic::ShowStudentResponse_<ContainerAllocator1> & lhs, const ::learning_topic::ShowStudentResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace learning_topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learning_topic::ShowStudentResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_topic::ShowStudentResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::ShowStudentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::ShowStudentResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::ShowStudentResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::ShowStudentResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_topic::ShowStudentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::learning_topic::ShowStudentResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_topic::ShowStudentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_topic/ShowStudentResponse";
  }

  static const char* value(const ::learning_topic::ShowStudentResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_topic::ShowStudentResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"\n"
;
  }

  static const char* value(const ::learning_topic::ShowStudentResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_topic::ShowStudentResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShowStudentResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_topic::ShowStudentResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::learning_topic::ShowStudentResponse_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_TOPIC_MESSAGE_SHOWSTUDENTRESPONSE_H
