// Generated by gencpp from file learning_topic/ShowStudentRequest.msg
// DO NOT EDIT!


#ifndef LEARNING_TOPIC_MESSAGE_SHOWSTUDENTREQUEST_H
#define LEARNING_TOPIC_MESSAGE_SHOWSTUDENTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace learning_topic
{
template <class ContainerAllocator>
struct ShowStudentRequest_
{
  typedef ShowStudentRequest_<ContainerAllocator> Type;

  ShowStudentRequest_()
    {
    }
  ShowStudentRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::learning_topic::ShowStudentRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::learning_topic::ShowStudentRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ShowStudentRequest_

typedef ::learning_topic::ShowStudentRequest_<std::allocator<void> > ShowStudentRequest;

typedef boost::shared_ptr< ::learning_topic::ShowStudentRequest > ShowStudentRequestPtr;
typedef boost::shared_ptr< ::learning_topic::ShowStudentRequest const> ShowStudentRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::learning_topic::ShowStudentRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::learning_topic::ShowStudentRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace learning_topic

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::learning_topic::ShowStudentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::learning_topic::ShowStudentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::ShowStudentRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::learning_topic::ShowStudentRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::ShowStudentRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::learning_topic::ShowStudentRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::learning_topic::ShowStudentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::learning_topic::ShowStudentRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::learning_topic::ShowStudentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "learning_topic/ShowStudentRequest";
  }

  static const char* value(const ::learning_topic::ShowStudentRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::learning_topic::ShowStudentRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::learning_topic::ShowStudentRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::learning_topic::ShowStudentRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ShowStudentRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::learning_topic::ShowStudentRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::learning_topic::ShowStudentRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // LEARNING_TOPIC_MESSAGE_SHOWSTUDENTREQUEST_H
